version: "3.4"

services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    volumes:
      - /ext-drive/data/minio:/data
    ports:
      - 8085:8085
      - 8086:8086
    environment:
      MINIO_ROOT_USER: systemadmin
      MINIO_ROOT_PASSWORD: systemadmin
      MINIO_ACCESS_KEY: systemuser
      MINIO_SECRET_KEY: systemuser
    command: server /data --console-address ":8086" --address ":8085"
